### ISSUE TITLE
Specifying python 3 classifiers in setup.py

### ISSUE THREAD

**Issue by tveastman** [ralphm/wokkel#20]
Hi! Tools like 'caniusepython3' examine the trove classifiers in pypi to determine if a library is python 3 ready.

Wokkel's .travisci.yml file specifies tests to run on 2.7, 3.3, and 3.5. It would be great to have equivalent trove classifiers specified in the setup.py. Should be as simple as:

```
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3.4
```

Cheers!

**Comment by ralphm** [comment]
Hi. This has been incorporated in the branch for the upcoming 18.0.0 release. See also #24.

**Comment by ralphm** [comment]
Please check out 18.0.0rc5 over at PyPI.
