### ISSUE TITLE
Wokkel release

### ISSUE THREAD

**Issue by micheloosterhof** [ralphm/wokkel#24]
Hello!
For another project (Cowrie), we are using Wokkel, but the latest release (not master tree) does not contain all the Py3 patches. Could you make another release from current master?

**Comment by micheloosterhof** [comment]
Hello! Have you had a chance to look at my request?

**Comment by ralphm** [comment]
Hi, @micheloosterhof. I cut 18.0.0rc1 last week. See https://pypi.python.org/pypi/wokkel/18.0.0rc1 and https://github.com/ralphm/wokkel/tree/release-18.0.0. Please check it out.

**Comment by ralphm** [comment]
With the release of 18.0.0 in #27, this is done.
